# Generated by Django 5.0.2 on 2024-02-14 19:15

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True 

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=20)),
                ('Description', models.TextField()),
                ('price', models.PositiveSmallIntegerField()),
                ('image', models.ImageField(upload_to='product_images/')),
            ],
        ),
    ]
