# Generated by Django 4.2.10 on 2024-02-18 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_user_first_name_user_last_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Careers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=255, verbose_name='Email')),
                ('full_name', models.CharField(max_length=200)),
                ('cover_letter', models.TextField()),
                ('cv', models.FileField(upload_to='cv')),
            ],
        ),
    ]
